version: "1"
rules: # Array of rules
  # - base: main # Required. Target branch
  #   upstream: lazyvim/starter:main # Required. Must be in the same fork network.
  #   mergeMethod: hardreset # Optional, one of [none, merge, squash, rebase, hardreset], Default: none.
  #   mergeUnstable: false # Optional, merge pull request even when the mergeable_state is not clean. Default: false
  - base: azmo
    upstream: lazyvim/starter:main # Required. Can be a branch in the same forked repo.
    reviewers: # Optional
      - azmodude
    conflictReviewers: # Optional, on merge conflict assign a reviewer
      - azmodude
    mergeMethod: rebase
label: ":arrow_heading_down: pull" # Optional
conflictLabel: "merge-conflict" # Optional, on merge conflict assign a custom label, Default: merge-conflict

