return {
  "nvim-treesitter/nvim-treesitter",
  opts = {
    -- leave all other options at lazyvim default
    auto_install = true,
    ensure_installed = {
      "bash",
      "c",
      "comment",
      "diff",
      "go",
      "git_rebase",
      "gitattributes",
      "gitcommit",
      "gitignore",
      "html",
      "javascript",
      "json",
      "lua",
      "luadoc",
      "luap",
      "markdown",
      "markdown_inline",
      "python",
      "query",
      "regex",
      "tsx",
      "typescript",
      "vim",
      "vimdoc",
      "yaml",
    },
  },
}
