name: Sync Fork

on:
  schedule:
    - cron: "*/30 * * * *" # every 30 minutes
  workflow_dispatch: # on button click
permissions:
  pull-requests: write

jobs:
  sync-fork-main:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          owner: lazyvim
          repo: starter
          base: main
          head: main
          auto_merge: true

  sync-fork-azmo:
    runs-on: ubuntu-latest
    steps:
      - uses: tgymnich/fork-sync@v2.0.10
        with:
          owner: lazyvim
          repo: starter
          base: azmo
          head: main
          auto_merge: false
          merge_method: merge
